### ISSUE TITLE
shared link not working

### ISSUE THREAD

**Issue by marcucci84** [onedata/getting-started#31]
At the moment I'm using Scenario3.0 with the onedata version rc11
I tried to use the sharing feature. I found these problems:
- the generated share link  has the format: https://onedata.org/ ... instead of https: // <mydomain> / ...
- I tried to rewrite the url, changing onedata.org with <mydomain>, but the link did not work.

**Comment by lopiola** [comment]
@marcucci84 The rc11 version had some bugs connected to share link generation, which were fixed in later releases. This is a quite old version, I would encourage using a newer one as they have more functionalities and less bugs. For share links to work correctly, you have to specify your zone's URL in docker-compose-yaml, under the key onezone -> domainName. This URL will be used to generate share links, but this is only supported in newer versions.

**Comment by marcucci84** [comment]
Thanks. I will try to install the new version.
